<?php 
if (!defined('BASEPATH')) exit('No direct script access allowed');

/**
* Yield  ::  HOOKS
*
* Adds layout support :: Similar to RoR <%= yield =>
* '{yield}' will be replaced with all output generated by the controller/view.
* 
* NOTE: Layouts are loaded independantly of controllers - this means that NO HELPERS LOADED IN CONTROLLERS 
* ARE AVAILABLE FOR USE BY THE LAYOUT. To use in the layout, you will need to re include the helpers needed.
*/
class Yield
{

  function doYield()
  {
    global $OUT;
  	
    //
    // load the controller output into the $output variable
    //
    $CI =& get_instance();
    $output = $CI->output->get_output();
    
    if (isset($CI->layout))
    {
    	//
    	// append the php extension if not specified
    	//
      if (!preg_match('/(.+).php$/', $CI->layout))
      {
        $CI->layout .= '.php';
      }

      $requested = APPPATH . 'views/layouts/' . $CI->layout;
      $default = APPPATH . 'views/layouts/default.php';
      $page_title = $CI->page_title;
      
      //
      // Load the requested (or default) layout into a string and replace the {yield}
      // delimeter with the controller output.
      //
      if (file_exists($requested))
      {
        $layout = $CI->load->file($requested, true);
        $view = str_replace("{yield}", $output, $layout);
      }
      else
      {
        $layout = $CI->load->file($default, true);
        $view = str_replace("{yield}", $output, $layout);
      }
      $view = str_replace("{page_title}", $page_title, $view);
    }
    
    //
    // if no layout is specified in the controller, simply render the controller output
    //
    else
    {
      $view = $output;
    }
    
    //
    // display the rendered string
    //
    $OUT->_display($view);
  }
}  

?>